version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: millionluxury-sqlserver
    environment:
      MSSQL_SA_PASSWORD: "YourStrong!Password123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P 'YourStrong!Password123' -Q 'SELECT 1' -C || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak-db:
    image: postgres:15-alpine
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: keycloak
    command: 
      - start-dev
      - --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak_password
      
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      
      KC_CACHE_STACK: tcp
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import:ro
    depends_on:
      keycloak-db:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  realestate-api:
    build:
      context: ../../
      dockerfile: tools/Docker/Dockerfile
    container_name: millionluxury-realestate-api
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://+:8081"
      ConnectionStrings__RealEstateDb: "Server=sqlserver,1433;Database=MillionLuxuryRealEstate;User Id=SA;Password=YourStrong!Password123;TrustServerCertificate=True;MultipleActiveResultSets=true"
      KeycloakConfiguration__Authority: "http://keycloak:8080/realms/realestate"
      KeycloakConfiguration__Audience: "realestate-api"
      KeycloakConfiguration__RequireHttpsMetadata: "false"
      KeycloakConfiguration__ValidateIssuer: "false"
      KeycloakConfiguration__ValidateAudience: "true"
      KeycloakConfiguration__ValidateLifetime: "true"
      KeycloakConfiguration__ValidateIssuerSigningKey: "true"
      KeycloakConfiguration__ClockSkew: "00:05:00"
      RunMigrationsOnStartup: "true"
    ports:
      - "8081:8081"
    depends_on:
      sqlserver:
        condition: service_healthy
      keycloak:
        condition: service_started
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  keycloak_db_data:
    driver: local
  sqlserver_data:
    driver: local

networks:
  app-network:
    driver: bridge
